name: CoronaCraft
version: ${project.version}
main: dev.nishappsucrose.coronacraft.CoronaCraft
api-version: 1.13
commands:
  home:
    description: Teleport back to lobby
  create:
    description: Create new CallCraft room
  join:
    description: Join room
  resetview:
    description: Teleport to room viewing area