name: CoronaCraft
version: ${project.version}
main: dev.nishappsucrose.coronacraft.CoronaCraft
api-version: 1.13
commands:
  loadstreams:
    description: Test map an image to a glass pane matrix
  origin:
    description: Teleport player back to viewing area